# Recap from the first week

In [89]:
values = [10, 20, 30, 40, 50]

In [90]:
values[1:4]
# [START:STOP:STEP] START = INCL , STOP = EXCL

[20, 30, 40]

In [91]:
values[::-1]

[50, 40, 30, 20, 10]

In [92]:
values[::-2]

[50, 30, 10]

A new list which contains the items in values multiplied by 2

In [93]:
# [x * 2 for x in values]
[x * 2 for x in values if x < 30]

[20, 40]

Duplicating the list but in 1 list

In [94]:
values * 2

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

# Week 2

In [95]:
import numpy as np # majority uses mp

In [96]:
numpy_values = np.array([1, 2, 3, 4])
print(numpy_values)

[1 2 3 4]


More efficient, less space, less overhead

In [97]:
numpy_values * 2

array([2, 4, 6, 8])

Different from Python list, instead of concatenating it performs an operation on every element in the array

In [98]:
values + values

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [99]:
numpy_values + numpy_values

array([2, 4, 6, 8])

---------------------------------------


In [100]:
a = np.array([1, 4, 2, 5, 3])

In [101]:
type(a)

numpy.ndarray

In [102]:
print(a.dtype)
a.dtype

int64


dtype('int64')

In [103]:
numpy_values = np.array([1, 2, 3, 4])
print(numpy_values)
numpy_values.dtype

[1 2 3 4]


dtype('int64')

In [104]:
numpy_values2 = np.array([1.13, 2, 3, 4])
print(numpy_values2)
numpy_values2.dtype

[1.13 2.   3.   4.  ]


dtype('float64')

numpy arrays can have only one single data type in them → converts the others to match it

In [105]:
numpy_values3 = np.array([1, 2, 3, 4], dtype='float32')
print(numpy_values3.dtype)
numpy_values3

float32


array([1., 2., 3., 4.], dtype=float32)

np array's can have multiple arguments, good to check the documentation, Py charm already shows it

In [106]:
numpy_values4 = np.array([1, 2.5, 3, 4], dtype='int64')
numpy_values4

array([1, 2, 3, 4])

----------------------------------------------------

In [107]:
arr1 = np.zeros(10, dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [108]:
arr2 = np.ones((3, 5), dtype=float)
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

ROWS ALWAYS COME FIRST in a two-dimensional array

In [109]:
arr3 = np.full((3,5), 3.14)
arr3

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [110]:
arr3.dtype

dtype('float64')

In [111]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [112]:
arr5 = np.arange(0, 10, 2)
arr5

array([0, 2, 4, 6, 8])

In [113]:
arr6 = np.linspace(0, 10, 5, endpoint=False) #10 is inclusive, with endpoint = False makes it excluded
arr6

array([0., 2., 4., 6., 8.])

In [114]:
arr7 = np.random.randint(0, 10, (3, 3))
arr7

array([[5, 1, 3],
       [0, 0, 9],
       [8, 4, 4]], dtype=int32)

In [115]:
rng = np.random.default_rng(42)
rng.integers(0, 10, (3,3))

array([[0, 7, 6],
       [4, 4, 8],
       [0, 6, 2]])

--------------------------------------

In [116]:
x = rng.integers(0, 10, size=(3,4))
x

array([[0, 5, 9, 7],
       [7, 7, 7, 5],
       [1, 8, 4, 5]])

In [117]:
x.ndim

2

In [118]:
x.shape

(3, 4)

In [119]:
x.size

12

In [120]:
x.dtype

dtype('int64')

In [121]:
x[2, 2]

np.int64(4)

In [122]:
x[0]

array([0, 5, 9, 7])

In [123]:
x[-1]

array([1, 8, 4, 5])

In [124]:
x

array([[0, 5, 9, 7],
       [7, 7, 7, 5],
       [1, 8, 4, 5]])

In [125]:
x[0, :2]

array([0, 5])

In [126]:
x[:, 1] # every row and column on index 1

array([5, 7, 8])

In [127]:
x[:, :2]

array([[0, 5],
       [7, 7],
       [1, 8]])

In [128]:
x[0, ::2]

array([0, 9])

In [129]:
x[:, ::-1]

array([[7, 9, 5, 0],
       [5, 7, 7, 7],
       [5, 4, 8, 1]])

In [130]:
x[::-1, ::-1] # reverses the table

array([[5, 4, 8, 1],
       [5, 7, 7, 7],
       [7, 9, 5, 0]])

---------------------------------------------------

In [131]:
b = np.arange(1, 11).reshape(2,5) # takes the long list and folds it
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [132]:
y = np.arange(1, 21).reshape(4,5)
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Retrieve:
1. 8
2. first row
3. last row
4. second column
5. last two columns
6. first two rows
7. the middle block [[7, 8, 9] and [12, 13, 14]]
8. every second column
9. rows in reverse order
10. columns in reverse order

In [133]:
y[1, 2] #1

np.int64(8)

In [134]:
y[0, :] #2

array([1, 2, 3, 4, 5])

In [135]:
y[-1, :] #3

array([16, 17, 18, 19, 20])

In [136]:
y[:, 1] #4

array([ 2,  7, 12, 17])

In [137]:
y[:, -2:] #5

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])

In [138]:
y[:2] #6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [139]:
y[1:3, 1:4] #7

array([[ 7,  8,  9],
       [12, 13, 14]])

In [140]:
y[:, ::2] #8

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

In [141]:
y[::-1] #9

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [142]:
y[:, ::-1] #10

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

-----------------------------------------------------

In [143]:
x = np.array([1, 2, 3, 4])

In [144]:
2 ** x

array([ 2,  4,  8, 16])

In [145]:
x = np.arange(3)
x

array([0, 1, 2])

In [146]:
x + 10

array([10, 11, 12])

In [147]:
x ** 2

array([0, 1, 4])

In [148]:
result = -(0.5 * x + 1)
result

array([-1. , -1.5, -2. ])

In [149]:
x / np.arange(1, 4)

array([0.        , 0.5       , 0.66666667])

matches the elements if you divide the array with another array

In [150]:
x / 2

array([0. , 0.5, 1. ])

In [151]:
np.power(3, x)
# the same as 3 ** x

array([1, 3, 9])

In [152]:
np.add(x, 3)

array([3, 4, 5])

In [153]:
np.add.reduce(x) # adds the elements in the array's together

np.int64(3)

In [154]:
np.sum(x) # 0 + 1 + 2

np.int64(3)

In [155]:
np.add.accumulate(x) # create accumulative sum

array([0, 1, 3])

In [156]:
x.cumsum()

array([0, 1, 3])

In [157]:
x.cumprod()
np.multiply.accumulate(x)

array([0, 0, 0])

In [158]:
vls = np.array([17, 22, 19, 26, 14, 24])
vls

array([17, 22, 19, 26, 14, 24])

In [159]:
%%time
converted = []

for value in vls:
    converted.append(value * 1.8 + 32)

converted

CPU times: total: 0 ns
Wall time: 69.9 μs


[np.float64(62.6),
 np.float64(71.6),
 np.float64(66.2),
 np.float64(78.80000000000001),
 np.float64(57.2),
 np.float64(75.2)]

for loops are not the way to do the thing above

In [160]:
%%time
vls * 1.8 + 32

CPU times: total: 0 ns
Wall time: 38.1 μs


array([62.6, 71.6, 66.2, 78.8, 57.2, 75.2])

Both fast, but the second one would remarkably faster in larger operations

Qs
Calculate:
1. All prices including 21% vat
2. a 2 euro discount on every price
3. the square of every price

In [161]:
prices = np.array([10, 12.5, 8, 20])

In [162]:
prices * 1.21

array([12.1  , 15.125,  9.68 , 24.2  ])

In [163]:
prices - 2

array([ 8. , 10.5,  6. , 18. ])

In [164]:
prices ** 2

array([100.  , 156.25,  64.  , 400.  ])

In [165]:
x = np.array([[1, 5, 3], [4, 2, 6]])

In [166]:
x.shape

(2, 3)

In [167]:
sum_of_array = x.sum()
print(sum_of_array)

21


In [168]:
x.min()

np.int64(1)

In [169]:
x.max()

np.int64(6)

In [170]:
x.std()

np.float64(1.707825127659933)

In [171]:
x.mean()

np.float64(3.5)

In [172]:
np.mean(x)

np.float64(3.5)

In [175]:
np.std(x)

np.float64(1.707825127659933)

In [176]:
np.median(x) # median can only be done with np.

np.float64(3.5)

In [177]:
Q1 = np.percentile(x, 25) # Q1

np.float64(2.25)

In [178]:
np.percentile(x, 50) # Q2

np.float64(3.5)

In [179]:
Q3 = np.percentile(x, 75) # Q3

np.float64(4.75)

In [182]:
np.percentile(x, 100) # Q4

np.float64(6.0)

In [185]:
Q1 = np.percentile(x, 25) # Q1
Q3 = np.percentile(x, 75) # Q3
iqr = Q3 - Q1
print(iqr)

2.5


In [186]:
x.sum(axis=0) # Row 1 = 1 + 4, Row 2 = 5 + 2 ,Row 3 = 6 + 3

array([5, 7, 9])

axis 0 is row dimension = collapse the columns
axis 1 is column dimension = collapse the row

In [187]:
x.sum(axis=1)

array([ 9, 12])

In [189]:
x.mean(axis=0)

array([2.5, 3.5, 4.5])

In [190]:
x.mean(axis=1)

array([3., 4.])

In [191]:
x.max(axis=1) # gets the max of each row = 2 rows 2 answers

array([5, 6])

In [192]:
x.max(axis=0) # gets the max of each column = 3 columns 3 answers

array([4, 5, 6])

## Broadcasting

In [199]:
x = np.arange(1, 13).reshape(3, 4) # reshape needs to match the amount of elements
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [201]:
offset = np.array([10, 20, 30, 40])
offset.shape

(4,)

In [197]:
x + offset

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 30, 41, 52]])

Stretches out because (3,4) and (1,4). As long as there is 1 there will be stretching. Offset goes to [[10, 20, 30, 40], [10, 20, 30, 40], [10, 20, 30, 40]]

In [202]:
print(x.shape)
print(offset.shape)

(3, 4)
(4,)


In [203]:
alternative_offset = np.array([10, 20, 30])

In [204]:
x + alternative_offset # doesn't work because nothing is equal

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [205]:
row_offset = np.array([100, 200, 300])

In [207]:
row_offset.shape

(3,)

In [209]:
row_offset = row_offset.reshape(3,1)
print(row_offset)
row_offset.shape

[[100]
 [200]
 [300]]


(3, 1)

In [210]:
x + row_offset

array([[101, 102, 103, 104],
       [205, 206, 207, 208],
       [309, 310, 311, 312]])

Boolean arrays, masks

In [211]:
x= np.array([
    [1, 5, 3],
    [4, 2, 6]
])

In [214]:
mask = x < 3
mask

array([[ True, False, False],
       [False,  True, False]])

In [215]:
np.sum(x < 3)

np.int64(2)

In [216]:
np.sum(x < 3, axis=1)

array([1, 1])

In [217]:
x < 5

array([[ True, False,  True],
       [ True,  True, False]])

In [218]:
np.any(x < 5)

np.True_

In [219]:
np.all(x < 5)

np.False_

In [220]:
np.all(x < 7)

np.True_

In [221]:
np.any(x < 5, axis=0) # mask OR

array([ True,  True,  True])

In [222]:
np.all(x < 5, axis=0) # mask AND

array([ True, False, False])

In [223]:
(x > 2) & (x < 5)

array([[False, False,  True],
       [ True, False, False]])

In [224]:
np.sum((x > 2) & (x < 5))

np.int64(2)

round brackets around dif conditions, no AND no OR

In [226]:
x[x < 5]

array([1, 3, 4, 2])

In [227]:
x2 = x.copy()

In [228]:
x2[x >= 5] = 0

In [230]:
x[x[:, 0] < 3]

array([[1, 5, 3]])

Fancy indexing

In [231]:
x = np.array([9, 7, 1, 5, 4])

In [233]:
x[[2, 4, 0]] # position 2, 4 and 0

array([1, 4, 9])

Questions:
1. Shape
2. Select Third column
3. calculate the mean score for each row
4. return all individual scores greater than or equal to 15
5. count how many scores are below 10
6. Select the element in the top left corner and bottom right in one statement

In [234]:
scores = np.array([
    [12, 15, 18],
    [8,  14, 14],
    [17, 19, 16],
    [10, 9,  13]]
)

In [235]:
scores.shape #1

(4, 3)

In [238]:
scores[:, -1] #2

array([18, 14, 16, 13])

In [251]:
np.mean(scores, axis=1) #3

array([15.        , 12.        , 17.33333333, 10.66666667])

In [253]:
array_higher_than_15 = scores[scores >= 15] #4
array_higher_than_15

array([15, 18, 17, 19, 16])

In [256]:
print(scores[scores < 10])
(scores < 10).sum()
print(np.sum(scores < 10))
# np.bincount(scores[scores < 10])

[8 9]
2


In [261]:
scores[(0, -1), (0, -1)]

array([12, 13])