# Recap from the first week

In [386]:
values = [10, 20, 30, 40, 50]

In [387]:
values[1:4]
# [START:STOP:STEP] START = INCL , STOP = EXCL

[20, 30, 40]

In [388]:
values[::-1]

[50, 40, 30, 20, 10]

In [389]:
values[::-2]

[50, 30, 10]

A new list which contains the items in values multiplied by 2

In [390]:
# [x * 2 for x in values]
[x * 2 for x in values if x < 30]

[20, 40]

Duplicating the list but in 1 list

In [391]:
values * 2

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

# Week 2

In [392]:
import numpy as np # majority uses mp

In [393]:
numpy_values = np.array([1, 2, 3, 4])
print(numpy_values)

[1 2 3 4]


More efficient, less space, less overhead

In [394]:
numpy_values * 2

array([2, 4, 6, 8])

Different from Python list, instead of concatenating it performs an operation on every element in the array

In [395]:
values + values

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [396]:
numpy_values + numpy_values

array([2, 4, 6, 8])

---------------------------------------


In [397]:
a = np.array([1, 4, 2, 5, 3])

In [398]:
type(a)

numpy.ndarray

In [399]:
print(a.dtype)
a.dtype

int64


dtype('int64')

In [400]:
numpy_values = np.array([1, 2, 3, 4])
print(numpy_values)
numpy_values.dtype

[1 2 3 4]


dtype('int64')

In [401]:
numpy_values2 = np.array([1.13, 2, 3, 4])
print(numpy_values2)
numpy_values2.dtype

[1.13 2.   3.   4.  ]


dtype('float64')

numpy arrays can have only one single data type in them → converts the others to match it

In [402]:
numpy_values3 = np.array([1, 2, 3, 4], dtype='float32')
print(numpy_values3.dtype)
numpy_values3

float32


array([1., 2., 3., 4.], dtype=float32)

np array's can have multiple arguments, good to check the documentation, Py charm already shows it

In [403]:
numpy_values4 = np.array([1, 2.5, 3, 4], dtype='int64')
numpy_values4

array([1, 2, 3, 4])

----------------------------------------------------

In [404]:
arr1 = np.zeros(10, dtype=int)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [405]:
arr2 = np.ones((3, 5), dtype=float)
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

ROWS ALWAYS COME FIRST in a two-dimensional array

In [406]:
arr3 = np.full((3,5), 3.14)
arr3

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [407]:
arr3.dtype

dtype('float64')

In [408]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [409]:
arr5 = np.arange(0, 10, 2)
arr5

array([0, 2, 4, 6, 8])

In [410]:
arr6 = np.linspace(0, 10, 5, endpoint=False) #10 is inclusive, with endpoint = False makes it excluded
arr6

array([0., 2., 4., 6., 8.])

In [411]:
arr7 = np.random.randint(0, 10, (3, 3))
arr7

array([[6, 1, 0],
       [8, 2, 6],
       [0, 5, 4]], dtype=int32)

In [412]:
rng = np.random.default_rng(42)
rng.integers(0, 10, (3,3))

array([[0, 7, 6],
       [4, 4, 8],
       [0, 6, 2]])

--------------------------------------

In [413]:
x = rng.integers(0, 10, size=(3,4))
x

array([[0, 5, 9, 7],
       [7, 7, 7, 5],
       [1, 8, 4, 5]])

In [414]:
x.ndim

2

In [415]:
x.shape

(3, 4)

In [416]:
x.size

12

In [417]:
x.dtype

dtype('int64')

In [418]:
x[2, 2]

np.int64(4)

In [419]:
x[0]

array([0, 5, 9, 7])

In [420]:
x[-1]

array([1, 8, 4, 5])

In [421]:
x

array([[0, 5, 9, 7],
       [7, 7, 7, 5],
       [1, 8, 4, 5]])

In [422]:
x[0, :2]

array([0, 5])

In [423]:
x[:, 1] # every row and column on index 1

array([5, 7, 8])

In [424]:
x[:, :2]

array([[0, 5],
       [7, 7],
       [1, 8]])

In [425]:
x[0, ::2]

array([0, 9])

In [426]:
x[:, ::-1]

array([[7, 9, 5, 0],
       [5, 7, 7, 7],
       [5, 4, 8, 1]])

In [427]:
x[::-1, ::-1] # reverses the table

array([[5, 4, 8, 1],
       [5, 7, 7, 7],
       [7, 9, 5, 0]])

---------------------------------------------------

In [428]:
b = np.arange(1, 11).reshape(2,5) # takes the long list and folds it
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [429]:
y = np.arange(1, 21).reshape(4,5)
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Retrieve:
1. 8
2. first row
3. last row
4. second column
5. last two columns
6. first two rows
7. the middle block [[7, 8, 9] and [12, 13, 14]]
8. every second column
9. rows in reverse order
10. columns in reverse order

In [430]:
y[1, 2] #1

np.int64(8)

In [431]:
y[0, :] #2

array([1, 2, 3, 4, 5])

In [432]:
y[-1, :] #3

array([16, 17, 18, 19, 20])

In [433]:
y[:, 1] #4

array([ 2,  7, 12, 17])

In [434]:
y[:, -2:] #5

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20]])

In [435]:
y[:2] #6

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [436]:
y[1:3, 1:4] #7

array([[ 7,  8,  9],
       [12, 13, 14]])

In [437]:
y[:, ::2] #8

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

In [438]:
y[::-1] #9

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [439]:
y[:, ::-1] #10

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16]])

-----------------------------------------------------

In [440]:
x = np.array([1, 2, 3, 4])

In [441]:
2 ** x

array([ 2,  4,  8, 16])

In [442]:
x = np.arange(3)
x

array([0, 1, 2])

In [443]:
x + 10

array([10, 11, 12])

In [444]:
x ** 2

array([0, 1, 4])

In [445]:
result = -(0.5 * x + 1)
result

array([-1. , -1.5, -2. ])

In [446]:
x / np.arange(1, 4)

array([0.        , 0.5       , 0.66666667])

matches the elements if you divide the array with another array

In [447]:
x / 2

array([0. , 0.5, 1. ])

In [448]:
np.power(3, x)
# the same as 3 ** x

array([1, 3, 9])

In [449]:
np.add(x, 3)

array([3, 4, 5])

In [450]:
np.add.reduce(x) # adds the elements in the array's together

np.int64(3)

In [451]:
np.sum(x) # 0 + 1 + 2

np.int64(3)

In [452]:
np.add.accumulate(x) # create accumulative sum

array([0, 1, 3])

In [453]:
x.cumsum()

array([0, 1, 3])

In [454]:
x.cumprod()
np.multiply.accumulate(x)

array([0, 0, 0])

In [455]:
vls = np.array([17, 22, 19, 26, 14, 24])
vls

array([17, 22, 19, 26, 14, 24])

In [456]:
%%time
converted = []

for value in vls:
    converted.append(value * 1.8 + 32)

converted

CPU times: total: 0 ns
Wall time: 71.8 μs


[np.float64(62.6),
 np.float64(71.6),
 np.float64(66.2),
 np.float64(78.80000000000001),
 np.float64(57.2),
 np.float64(75.2)]

for loops are not the way to do the thing above

In [457]:
%%time
vls * 1.8 + 32

CPU times: total: 0 ns
Wall time: 58.9 μs


array([62.6, 71.6, 66.2, 78.8, 57.2, 75.2])

Both fast, but the second one would remarkably faster in larger operations

Qs
Calculate:
1. All prices including 21% vat
2. a 2 euro discount on every price
3. the square of every price

In [458]:
prices = np.array([10, 12.5, 8, 20])

In [459]:
prices * 1.21

array([12.1  , 15.125,  9.68 , 24.2  ])

In [460]:
prices - 2

array([ 8. , 10.5,  6. , 18. ])

In [461]:
prices ** 2

array([100.  , 156.25,  64.  , 400.  ])

In [462]:
x = np.array([[1, 5, 3], [4, 2, 6]])

In [463]:
x.shape

(2, 3)

In [464]:
sum_of_array = x.sum()
print(sum_of_array)

21


In [465]:
x.min()

np.int64(1)

In [466]:
x.max()

np.int64(6)

In [467]:
x.std()

np.float64(1.707825127659933)

In [468]:
x.mean()

np.float64(3.5)

In [469]:
np.mean(x)

np.float64(3.5)

In [470]:
np.std(x)

np.float64(1.707825127659933)

In [471]:
np.median(x) # median can only be done with np.

np.float64(3.5)

In [472]:
Q1 = np.percentile(x, 25) # Q1

In [473]:
np.percentile(x, 50) # Q2

np.float64(3.5)

In [474]:
Q3 = np.percentile(x, 75) # Q3

In [475]:
np.percentile(x, 100) # Q4

np.float64(6.0)

In [476]:
Q1 = np.percentile(x, 25) # Q1
Q3 = np.percentile(x, 75) # Q3
iqr = Q3 - Q1
print(iqr)

2.5


In [477]:
x.sum(axis=0) # Row 1 = 1 + 4, Row 2 = 5 + 2 ,Row 3 = 6 + 3

array([5, 7, 9])

axis 0 is row dimension = collapse the columns
axis 1 is column dimension = collapse the row

In [478]:
x.sum(axis=1)

array([ 9, 12])

In [479]:
x.mean(axis=0)

array([2.5, 3.5, 4.5])

In [480]:
x.mean(axis=1)

array([3., 4.])

In [481]:
x.max(axis=1) # gets the max of each row = 2 rows 2 answers

array([5, 6])

In [482]:
x.max(axis=0) # gets the max of each column = 3 columns 3 answers

array([4, 5, 6])

## Broadcasting

In [483]:
x = np.arange(1, 13).reshape(3, 4) # reshape needs to match the amount of elements
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [484]:
offset = np.array([10, 20, 30, 40])
offset.shape

(4,)

In [485]:
x + offset

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 30, 41, 52]])

Stretches out because (3,4) and (1,4). As long as there is 1 there will be stretching. Offset goes to [[10, 20, 30, 40], [10, 20, 30, 40], [10, 20, 30, 40]]

In [486]:
print(x.shape)
print(offset.shape)

(3, 4)
(4,)


In [487]:
alternative_offset = np.array([10, 20, 30])

In [488]:
# x + alternative_offset # doesn't work because nothing is equal

In [489]:
row_offset = np.array([100, 200, 300])

In [490]:
row_offset.shape

(3,)

In [491]:
row_offset = row_offset.reshape(3,1)
print(row_offset)
row_offset.shape

[[100]
 [200]
 [300]]


(3, 1)

In [492]:
x + row_offset

array([[101, 102, 103, 104],
       [205, 206, 207, 208],
       [309, 310, 311, 312]])

Boolean arrays, masks

In [493]:
x= np.array([
    [1, 5, 3],
    [4, 2, 6]
])

In [494]:
mask = x < 3
mask

array([[ True, False, False],
       [False,  True, False]])

In [495]:
np.sum(x < 3)

np.int64(2)

In [496]:
np.sum(x < 3, axis=1)

array([1, 1])

In [497]:
x < 5

array([[ True, False,  True],
       [ True,  True, False]])

In [498]:
np.any(x < 5)

np.True_

In [499]:
np.all(x < 5)

np.False_

In [500]:
np.all(x < 7)

np.True_

In [501]:
np.any(x < 5, axis=0) # mask OR

array([ True,  True,  True])

In [502]:
np.all(x < 5, axis=0) # mask AND

array([ True, False, False])

In [503]:
(x > 2) & (x < 5)

array([[False, False,  True],
       [ True, False, False]])

In [504]:
np.sum((x > 2) & (x < 5))

np.int64(2)

round brackets around dif conditions, no AND no OR

In [505]:
x[x < 5]

array([1, 3, 4, 2])

In [506]:
x2 = x.copy()

In [507]:
x2[x >= 5] = 0

In [508]:
x[x[:, 0] < 3]

array([[1, 5, 3]])

Fancy indexing

In [509]:
x = np.array([9, 7, 1, 5, 4])

In [510]:
x[[2, 4, 0]] # position 2, 4 and 0

array([1, 4, 9])

Questions:
1. Shape
2. Select Third column
3. calculate the mean score for each row
4. return all individual scores greater than or equal to 15
5. count how many scores are below 10
6. Select the element in the top left corner and bottom right in one statement

In [511]:
scores = np.array([
    [12, 15, 18],
    [8,  14, 14],
    [17, 19, 16],
    [10, 9,  13]]
)

In [512]:
scores.shape #1

(4, 3)

In [513]:
scores[:, -1] #2

array([18, 14, 16, 13])

In [514]:
np.mean(scores, axis=1) #3

array([15.        , 12.        , 17.33333333, 10.66666667])

In [515]:
array_higher_than_15 = scores[scores >= 15] #4
array_higher_than_15

array([15, 18, 17, 19, 16])

In [516]:
print(scores[scores < 10])
(scores < 10).sum()
print(np.sum(scores < 10))
# np.bincount(scores[scores < 10])

[8 9]
2


In [517]:
scores[(0, -1), (0, -1)]

array([12, 13])

-----------------------------------------------------


In [518]:
import pandas as pd

In [519]:
population = pd.Series(
    [11.7, 17.7],
    index=["be", "nl"]
)

population

be   11
nl   17
dtype: float64

In [520]:
population["be"]

np.float64(11.7)

In [521]:
population.values

array([11.7, 17.7])

In [522]:
type(population.values)

numpy.ndarray

In [523]:
type(population)

pandas.Series

In [524]:
population.index

Index(['be', 'nl'], dtype='str')

In [525]:
population.dtype

dtype('float64')

In [526]:
population_dict = {
    "be" : 11.7,
    "nl" : 17.7
}

In [527]:
%%time

population2 = pd.Series(population_dict)

CPU times: total: 0 ns
Wall time: 379 μs


In [528]:
population2

be   11
nl   17
dtype: float64

------ DATAFRAMES ------

In [529]:
countries_dict = {
    "population": [11.7, 17.7],
    "area": [30688, 41850]
}

In [530]:
countries = pd.DataFrame(countries_dict, index=["be", "nl"])
countries

,population,area
be,11,30688
nl,17,41850


In [531]:
countries.shape

(2, 2)

In [532]:
countries.columns

Index(['population', 'area'], dtype='str')

In [533]:
countries.index

Index(['be', 'nl'], dtype='str')

In [534]:
countries.dtypes

population    float64
area            int64
dtype: object

In [536]:
countries.info()

<class 'pandas.DataFrame'>
Index: 2 entries, be to nl
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   population  2 non-null      float64
 1   area        2 non-null      int64  
dtypes: float64(1), int64(1)
memory usage: 156.0+ bytes


In [537]:
countries.describe()

,population,area
count,2,2
mean,14,36269
std,4,7892
min,11,30688
25%,13,33478
50%,14,36269
75%,16,39059
max,17,41850


In [545]:
df_presidents = pd.read_csv("president_heights.csv", index_col='order') # sep=";" for semicolon separations dtype={'height(cm)': float}) for EDIT DOMAIN

In [544]:
df_presidents.head()

,name,height(cm)
order,,
1,George Washington,189
2,John Adams,170
3,Thomas Jefferson,189
4,James Madison,163
5,James Monroe,183


In [547]:
df_presidents.dtypes

name            str
height(cm)    int64
dtype: object

In [548]:
df_presidents.head(10)

,name,height(cm)
order,,
1,George Washington,189
2,John Adams,170
3,Thomas Jefferson,189
4,James Madison,163
5,James Monroe,183
6,John Quincy Adams,171
7,Andrew Jackson,185
8,Martin Van Buren,168
9,William Henry Harrison,173


In [549]:
df_presidents.tail(5)

,name,height(cm)
order,,
40,Ronald Reagan,185
41,George H. W. Bush,188
42,Bill Clinton,188
43,George W. Bush,182
44,Barack Obama,185


In [550]:
df_presidents.shape

(42, 2)

In [551]:
df_presidents.columns

Index(['name', 'height(cm)'], dtype='str')

In [552]:
df_presidents.info()

<class 'pandas.DataFrame'>
Index: 42 entries, 1 to 44
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        42 non-null     str  
 1   height(cm)  42 non-null     int64
dtypes: int64(1), str(1)
memory usage: 1008.0 bytes


In [565]:
data = pd.Series(['a', 'b', 'c'], index=[1, 5, 3])

In [554]:
data

1    a
3    b
5    c
dtype: str

INDEX' in pandas is explicit so index 1 = position 1, not 0

In [555]:
data[1]

'a'

In [556]:
data[1:3]

3    b
5    c
dtype: str

In pandas we never use explicit labeling

In [558]:
data.loc[1] # give me the data with the explicit label 1

'a'

In [560]:
data.iloc[1] # give me the integer location of index 1

'b'

In [561]:
data.iloc[0]

'a'

In [566]:
data.loc[1:3] # UPPER BOUNDARY IS INCLUDED WITH LOC. It takes the index label of 1 and 3 and displays what's between those


1    a
5    b
3    c
dtype: str

In [567]:
countries

,population,area
be,11,30688
nl,17,41850


In [570]:
# countries['population']
countries.population # no need for these

be   11
nl   17
Name: population, dtype: float64

In [571]:
type(countries['population'])

pandas.Series

In [575]:
countries["density"] = (countries["population"] / countries["area"])

countries

,population,area,density
be,11,30688,0
nl,17,41850,0


In [582]:
countries.loc["be"]

population      11
area         30688
density          0
Name: be, dtype: float64

In [583]:
countries.loc["be", "area"]

np.int64(30688)

In [584]:
countries.loc[:, ["population", "density"]]

,population,density
be,11,0
nl,17,0


In [589]:
countries.loc[:,"population":"area"] # include last one

,population,area
be,11,30688
nl,17,41850


In [590]:
countries.iloc[0] # pycharm will show as column but it's the first row

population      11
area         30688
density          0
Name: be, dtype: float64

In [591]:
countries.iloc[0, 1]

np.int64(30688)

In [593]:
countries.iloc[:, :2] # but not including 2

,population,area
be,11,30688
nl,17,41850


In [594]:
countries["population"] > 15

be    False
nl     True
Name: population, dtype: bool

In [597]:
countries[countries["population"] > 15] # boolean mask

,population,area,density
nl,17,41850,0


In [599]:
countries.loc[countries["population"] > 15] # the same as above

,population,area,density
nl,17,41850,0
